version: '2'
services:
    nodejs:
        image: node:13.0-alpine
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        ports:
            - "8080:8080"
        command: "yarn dev"
        # environment:
        #     - REDIS_URL=redis://redis-app
    redis:
        container_name: redis-app
        image: redis
        ports:
            - "6379:6379"